### ISSUE TITLE
[CLI] Add golismero support

### ISSUE THREAD

**Issue by katopz** [rabbotio/eyes-cli#5]
- [x] Learn how to construct `golismero` Dockerfile from [golismero-suite](https://github.com/rabbotio/golismero-suite/blob/master/golismero/Dockerfile) and add `Dockerfile` to repos `rabbotio/golismero`.
- [x] Change [source repos](https://github.com/rabbotio/golismero-suite/blob/master/golismero/Dockerfile#L19) to https://github.com/golismero/golismero
- [x] Make it scan by `docker run` with target `url`.
- [x] Export as `html`.
- [x] Push to `Docker Hub`.
- [x] Add as `eyes-cli` tool.
- [x] Ensure `html` result is deploy to [Firebase hosting](https://eyes-ed226.firebaseapp.com/).

**Comment by niponchi** [comment]
- added Dockerfile
- image pushed to docker hub `rabbotio/golismero`
- note: does not support openVAS and SpiderFoot
- export to html by using `-o filename.html`, with extension html, the tool write output as html
- output is a single html file, so it should be fine with Firebase hosting

*example command:* note that ~/output/golismer need a write permission
```
docker run --rm -ti -v ~/output/golismer:/opt/golismer/result:rw rabbotio/golismero scan http://example.com -o /opt/golismer/result/output.html
```

**Comment by katopz** [comment]
Great job! 👍

**Comment by niponchi** [comment]
added support in `eyes-cli` tool
```
node eyes golismero --url http://rabbot.io
```
